### ISSUE TITLE
Large chunks cause error when creating transaction

### ISSUE THREAD

**Issue by elliotsayes** [CDDelta/arweave-stream-tx#2]
When streaming files from AWS S3:
```ts
import { S3 } from 'aws-sdk';
// ...
const s3 = new S3({region: regionName})
const obj = s3.getObject({
  Bucket: bucketName,
  Key: filePath,
})
const stream = obj.createReadStream()
const transaction = await pipeline(stream, createTransactionAsync({}, arweave, jwk))
```
Some files trigger: 
`Error: Encountered chunk larger than max chunk size.`
From https://github.com/CDDelta/arweave-stream-tx/blob/master/src/generate-transaction-chunks-async.ts#L80

Am I doing something wrong here or is this a limitation of the library?

**Comment by CDDelta** [comment]
This has been fixed as a part of the latest release, `1.2.0`. Thank you!
